Repository arduino/nicla-sense-me-fw, pull requests merged in 2023-11, with the labels that each got.

#113 Add missing documentation
  Arduino_BHY2/src/BoschSensortec.h
  Arduino_BHY2/src/sensors/SensorTypes.h
Labels: bug, documentation

#115 [AE-45] Check License in base repo, Arduino_BHY2 and Arduino_BHY2Host
  .github/workflows/check-license.yml
  .vscode/easycode.ignore
  README.md
Labels: documentation, enhancement

#116 [AE-45] Add `spell-check-task.yml`
  .github/workflows/spell-check-task.yml
  README.md
  Taskfile.yml
  codespellrc
  pyproject.toml
Labels: documentation, enhancement

#120 Fix spelling of Bosch library files
  Arduino_BHY2/src/bosch/bhy2.h
  Arduino_BHY2/src/bosch/bhy2_defs.h
  Arduino_BHY2/src/bosch/bhy2_hif.h
  bootloader/BHY2-Sensor-API/bhy2.h
  bootloader/BHY2-Sensor-API/bhy2_defs.h
  bootloader/BHY2-Sensor-API/bhy2_hif.h
Labels: documentation

#121 Make Spell-check workflow happy 😊
  .codespellrc
  Arduino_BHY2/docs/readme.md
  Arduino_BHY2/examples/BHYFirmwareUpdate/conv.sh
  Arduino_BHY2/examples/BSEC2GasScannerClassify/BSEC2GasScannerClassify.ino
  Arduino_BHY2/examples/BSEC2GasScannerCollectData/tools/BSEC2DataLogConverter.py
  Arduino_BHY2/examples/DataHarvester/extras/Commander/Commander.py
  Arduino_BHY2/examples/StandaloneFlashStorage/StandaloneFlashStorage.ino
  Arduino_BHY2/src/Arduino_BHY2.h
  Arduino_BHY2/src/BLEHandler.h
  Arduino_BHY2/src/BoschParser.h
  Arduino_BHY2/src/BoschSensortec.h
  Arduino_BHY2/src/DFUManager.h
  Arduino_BHY2/src/EslovHandler.h
  Arduino_BHY2/src/sensors/DataParser.h
  Arduino_BHY2Host/src/Arduino_BHY2Host.h
  Arduino_BHY2Host/src/BLEHandler.h
  Arduino_BHY2Host/src/EslovHandler.h
  Arduino_BHY2Host/src/sensors/DataParser.h
  README.md
  bootloader/examples/Blink_Unisense/Blink_Unisense.ino
  bootloader/src/BQ25120A.h
  bootloader/src/IS31FL3194.h
  bootloader/src/led_driver.cpp
Labels: bug, documentation

#117 Bump release workflow to match the template in the tooling-project-assets repository
  .github/workflows/release-go-task.yml
  DistTasks.yml
  gon.config.hcl
Labels: enhancement
